# Generated by Django 2.1.7 on 2019-03-01 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20, verbose_name='类型名称')),
            ],
            options={
                'db_table': 'blogtype',
                'verbose_name_plural': '博客类型',
                'verbose_name': '博客类型',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=20, verbose_name='分类名称')),
            ],
            options={
                'db_table': 'category',
                'verbose_name_plural': '分类名称',
                'verbose_name': '分类名称',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('reply_time', models.DateField(auto_now=True, verbose_name='评论时间')),
            ],
            options={
                'db_table': 'reply',
                'verbose_name_plural': '回复内容',
                'verbose_name': '回复内容',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('pub_date', models.DateField(auto_now=True, verbose_name='发表时间')),
                ('read_num', models.IntegerField(default=0, null=True, verbose_name='阅读量')),
                ('content', models.TextField(verbose_name='内容')),
                ('images', models.ImageField(default=None, null=True, upload_to='static/images', verbose_name='图片')),
                ('blogtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.BlogType')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Category')),
            ],
            options={
                'db_table': 'topic',
                'verbose_name_plural': '博客信息',
                'verbose_name': '博客信息',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30, verbose_name='用户名')),
                ('uemail', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('uurl', models.CharField(max_length=100, verbose_name='个人主站网址')),
                ('upwd', models.CharField(max_length=200)),
                ('isActive', models.BooleanField(default=False, verbose_name='是否是作者')),
            ],
            options={
                'db_table': 'users',
                'verbose_name_plural': '用户信息',
                'verbose_name': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='Voke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Topic')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Users')),
            ],
            options={
                'db_table': 'voke',
                'verbose_name_plural': '点赞详情',
                'verbose_name': '点赞详情',
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Users'),
        ),
        migrations.AddField(
            model_name='reply',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Topic'),
        ),
        migrations.AddField(
            model_name='reply',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Users'),
        ),
    ]
